" Written by Aron Griffis <agriffis@gentoo.org>
" Modified by Ryan Phillips <rphillips@gentoo.org>
" Added Redhat's vimrc info by Seemant Kulleen <seemant@gentoo.org>
" Added some enhancements by A. Murat Eren <meren@uludag.org.tr>
" Tidy up by Onur Küçük <onur@pardus.org.tr>
" Some good stuff is taken from Derek Wyatt's Vim Configuration <http://github.com/derekwyatt>
" Some more good stuff is taken from Fatih Arslan's Vim Configuration <http://github.com/farslan>
" Bundled and modified by Doğukan Çağatay <http://github.com/dogukancagatay>

" Install monokai color scheme
if empty(glob('~/.vim/colors/monokai.vim'))
  silent !curl -fLo ~/.vim/colors/monokai.vim --create-dirs
    \ https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
  autocmd VimEnter * source $MYVIMRC
endif

" Install vim-plug plugin manager
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" vim-plug plugin listing
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-eunuch'
Plug 'airblade/vim-gitgutter'
Plug 'editorconfig/editorconfig-vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdcommenter'
Plug 'ctrlpvim/ctrlp.vim'

call plug#end()

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
set backspace=2         " same as :set backspace=indent,eol,start

" Indentation settings
set autoindent          " Always set auto-indenting on
set tabstop=4
set shiftwidth=4

" Add a newline after each occurrence of the last search term
nnoremap SS :%s//&\r/<CR>

" Vi is cooler with these settings :)
set sta
set sts=4
set expandtab

set viminfo='20,\"50    " Read/write a .viminfo file -- limit to only 50
set history=100         " Keep 100 lines of command history
set ruler               " Show the cursor position all the time
set showmode            " Show current mode

" Set syntax coloring on
syntax enable
filetype on
filetype plugin on
filetype indent on

" Search options
set showmatch
set incsearch           " shows matching while typing
set ignorecase
set hlsearch            " highlight found searches

" Encoding options
set encoding=utf8
set tenc=utf8
set fileencoding=utf8
set fileformats=unix,dos,mac    " Prefer unix over windows over os9 formats

set wrap                " wrap long lines to windows width by word
set number              " show line numbers
set linebreak
set laststatus=2
set showcmd             " shows what you are typing as a command
set wildmenu            " Make the command-line completion better
set showfulltag         " When completing by tag, show the whole tag, not just the function name
set autoread            " Automatically read a file that has changed on disk
set splitright          " Split vertical windows right to the current windows
set splitbelow          " Split horizontal windows below to the current windows
set mat=5               " show matching for an half sec

set mouse=a             " Use mouse wheel to scroll up/down

" vim-airline settings
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='molokai'

" vim-gitgutter settings
set updatetime=250

" Cool tab completion stuff
set wildmenu
set wildmode=list:longest,full

" Theme settings
" colorscheme elflord
colorscheme monokai

" make vim save and load the folding of the document each time it loads
" also places the cursor in the last place that it was left.
set viewdir=/tmp
au BufWinLeave * silent! mkview
au BufWinEnter * silent! loadview

" #####################
" # Mappings
" ####################

" This comes first, because there are mappings that depend on leader
let mapleader = ","
let g:mapleader = ","

" Enable syntastic check on file save
" https://github.com/scrooloose/syntastic/issues/1391
noremap :w<CR> :w<CR>:SyntasticCheck<CR>

" Getting sudo rights from inside of vim
command W w !sudo tee % >/dev/null

" CTRL+N x2 shows line numbers
nmap <C-N><C-N> :set invnumber <CR>

" open spell checker
map <leader>spell :setlocal spell! <CR><CR>

" Do a syntastic Check
map <leader>ss :SyntasticCheck <CR><CR>

" Enables to move upward/downward at long lines
map <UP> gk
map <DOWN> gj
map k gk
map j gj

" Tab controls
nmap <leader>t :tabnew<CR>
nmap <leader>n :tabprevious<CR>
nmap <leader>m :tabnext<CR>

" CtrlP leader mappings
nmap <leader>f :CtrlPMixed<CR>
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.tar.gz     " MacOSX/Linux

" force close/write and close
nmap <leader>q :q!<CR>
nmap <leader>qa :qa!<CR>
nmap <leader>wq :wq!<CR>
nmap <leader>wqa :wqa!<CR>
nmap <leader>w :w<CR>

" toggle paste mode with leader + p
nmap <leader>p :set paste!<CR>

" nerdcommenter
nmap <leader>cc NERDComToggleComment

" nerdtree
nmap <leader>b <plug>NERDTreeTabsToggle<CR>

" Enable extended regex vim search
nnoremap / /\v
vnoremap / /\v

" compile and run single java files
map <F9> :w<CR>:set makeprg=javac\ %<CR>:make<CR>
map <F10> :!echo %\|awk -F. '{print $1}'\|xargs java<CR>

" Substitution function for Turkish characters with Latex Turkish characters
function! Tr_char_to_latex()
    :%s/ğ\|Ğ\|ç\|Ç\|ş\|Ş\|ü\|Ü\|ö\|Ö\|ı\|İ/\={'ğ':'\u{g}','Ğ':'\u{G}','ç':'\c{c}','Ç':'\c{C}','ş':'\c{s}','Ş':'\c{S}','ü':'\"{u}','Ü':'\"{U}','ö':'\"{o}','Ö':'\"{O}','ı':'{\i}','İ':'\.{I}'}[submatch(0)]/g
endfunction

" Changes file encoding to utf-8 and file format to unix
function! Dos2unix()
    :set fileformat=unix | set fileencoding=utf8 | %s///g
endfunction

" Prettify JSON file
function! JsonPrettyfy()
    :%!python -m json.tool
endfunction

" Fix for corrupted Turkish characters because of encoding changes
function! Tr_char_fix()
    :call Dos2unix() | %s/Ý\|ý\|Þ\|þ\|Ð\|ð/\={'ð':'ğ','Ð':'Ğ','þ':'ş','Þ':'Ş','ý':'ı','Ý':'İ'}[submatch(0)]/g
endfunction

" #####################
" # Auto commands
" ####################
"
autocmd FileType sml setlocal makeprg=sml\ '%'
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType yml setlocal ts=2 sts=2 sw=2 expandtab

" Open NERDTree automatically when vim starts up
autocmd vimenter * NERDTree | wincmd p

" How can I close vim if the only window left open is a NERDTree?
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" If the filetype is Makefile then we need to use tabs
" So do not expand tabs into space.
if has("autocmd")
    autocmd FileType make set noexpandtab
endif
