## oh-my-zsh settings
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="pardus"
# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
plugins=(cp git osx macports python github autojump gnu-utils sbt scala history-substring-search mvn rake extract zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

## My Settings
#Lang
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#Defaults
export EDITOR="vim"
export VISUAL="vim"
export PAGER=less
export LC_CTYPE=$LANG
export TERM="xterm-256color"

#Completion
unsetopt flowcontrol
unsetopt menu_complete   # don't select the first entry automatically

#History
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

setopt hist_ignore_dups # ignore duplication command history list
setopt hist_verify
setopt inc_append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_space

#Aliases
if [ -f ~/.bash/aliases ]; then
    source ~/.bash/aliases
fi

if [ -f ~/.bash_profile2 ]; then
    source ~/.bash_profile2
fi

## Functions
if [ -f ~/.bash/funcs ]; then
    source ~/.bash/funcs
fi

## Mac OS X dependent settings
if [ $(uname -s) = "Darwin" ]; then

  # latex binaries
  PATH=$PATH:"/usr/local/texlive/2012/bin/x86_64-darwin"

  export SHELL=/opt/local/bin/zsh

  # gnubin utils installed with macports
  export PATH="/opt/local/libexec/gnubin:$PATH"

  # MacPorts Installer addition 
  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
  export MANPATH="$MANPATH:/opt/local/share/man"
  export INFOPATH="$INFOPATH:/opt/local/share/info"

  if [ -f /opt/local/etc/profile.d/autojump.zsh ]; then
      source /opt/local/etc/profile.d/autojump.zsh
      autoload -U compinit && compinit -u
      export AUTOJUMP_IGNORE_CASE=1
      export AUTOJUMP_KEEP_SYMLINKS=1
  fi
fi

## autojump for linux is not tested
## Linux
if [ $(uname -s) = "Linux" ]; then

    export SHELL=/bin/zsh

    # autojump for bash (ubuntu package)
    if [ -f /usr/share/autojump/autojump.zsh ]; then
        . /usr/share/autojump/autojump.zsh
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    ## On Arch Linux it is installed under /usr/etc/
    if [ -f /usr/etc/profile.d/autojump.zsh ]; then
        . /usr/etc/profile.d/autojump.zsh
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi
fi

# Add home bin to the PATH
if [ -d ~/bin ]; then
  export PATH=$PATH:$HOME"/bin"
fi

