# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="pardus"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(cp git osx macports python github autojump gnu-utils sbt scala history-substring-search mvn rake extract zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

#My Settings

#Lang
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#Defaults
export EDITOR="vim"
export VISUAL="vim"

#Completion
unsetopt flowcontrol
unsetopt menu_complete   # don't select the first entry automatically

#History
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

setopt hist_ignore_dups # ignore duplication command history list
setopt hist_verify
setopt inc_append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_space

#Pager
export PAGER=less
export LC_CTYPE=$LANG

#Aliases
alias ls="ls --color=auto"
alias ll="ls --color -lha"
alias la="ls --color -la"
alias grep="grep --color"
alias pgrep="pgrep -f"
alias pkill="pkill -f"
alias egrep="egrep --color"
alias fgrep="fgrep --color"
alias cls="clear"
alias cd..="cd .."
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i" 
alias ln="ln -i"
alias wget='wget -c'
alias df='df -h'
alias du='du -h'
alias free='free -m'

alias diff='colordiff'      # install colordiff package :)
alias path='echo -e ${PATH//:/\\n}'
alias ping='ping -c 5'
alias ports='netstat -tulanp tcp'
alias bc='bc -l' # run with standard math lib

# tree command
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

##git
# pretty log
alias gitlg="git log --graph --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr)%Creset%C(yellow)%d%Creset %C(dim white)%an%Creset' --abbrev-commit --date=relative --date-order --all" 

#detailed commit logs
alias gitcilg='git log --pretty=format:"[%h] %ae, %ar: %s" --stat'

## Mac OS X dependent settings
if [ $(uname -s) = "Darwin" ]; then

  # latex binaries
  PATH=$PATH:"/usr/local/texlive/2012/bin/x86_64-darwin"

  export SHELL=/opt/local/bin/zsh

  # tree
  alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

  # gnubin utils installed with macports
  export PATH="/opt/local/libexec/gnubin:$PATH"

  # MacPorts Installer addition 
  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
  export MANPATH="$MANPATH:/opt/local/share/man"
  export INFOPATH="$INFOPATH:/opt/local/share/info"

  if [ -f /opt/local/etc/profile.d/autojump.zsh ]; then
      source /opt/local/etc/profile.d/autojump.zsh
      autoload -U compinit && compinit -u
      export AUTOJUMP_IGNORE_CASE=1
      export AUTOJUMP_KEEP_SYMLINKS=1
  fi
fi

## autojump for linux is not tested
## Linux
if [ $(uname -s) = "Linux" ]; then

    export SHELL=/bin/zsh

    # autojump for bash (ubuntu package)
    if [ -f /usr/share/autojump/autojump.zsh ]; then
        . /usr/share/autojump/autojump.zsh
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    ## On Arch Linux it is installed under /usr/etc/
    if [ -f /usr/etc/profile.d/autojump.zsh ]; then
        . /usr/etc/profile.d/autojump.zsh
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi
fi

# Add home bin to the PATH
if [ -d ~/bin ]; then
  export PATH=$PATH:$HOME"/bin"
fi
