#PS1='\u@\h:\W \$ '
PS1='\[\033[1m\]\u@\h \[\033[0;31m\]\W \$ \[\033[00m\]'

# set SHELL
if [ -f /opt/local/bin/bash ]; then
    SHELL="/opt/local/bin/bash"
else
    SHELL="/bin/bash"
fi

export SHELL=/bin/bash

# make bash history unlimited
export HISTFILESIZE=
export HISTSIZE=

# set editor as vim
export EDITOR="vim"
export PAGER="less"

#vi-compatiple command line
set -o vi

# Language preferences
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

CLICOLOR=1

## Mac OS X dependent settings
if [ $(uname -s) = "Darwin" ]; then

    # QT bin on osx
    #PATH=$PATH:$HOME"/QtSDK/Desktop/Qt/474/gcc/bin"

    # php installation configuration from http://php-osx.liip.ch/
    if [ -e /usr/local/php5/bin ]; then
        PATH="/usr/local/php5/bin":$PATH
    fi

    # gnubin utils installed with macports
    PATH="/opt/local/libexec/gnubin:$PATH"

    # gnuplot
    export GNUTERM=X11
    
    #texlive 2013
    PATH=/usr/local/texlive/2013/bin/x86_64-linux:~/bin:$PATH
    MANPATH=/usr/local/texlive/2013/texmf-dist/doc/man:$MANPATH
    INFOPATH=/usr/local/texlive/2013/texmf-dist/doc/info:$INFOPATH

    # MacPorts Installer addition 
    export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
    export MANPATH="$MANPATH:/opt/local/share/man"
    export INFOPATH="$INFOPATH:/opt/local/share/info"

    # Java home
    export JAVA_HOME=$(/usr/libexec/java_home)

    # autojump for bash installed with macports
    if [ -f /opt/local/etc/profile.d/autojump.sh ]; then
        source /opt/local/etc/profile.d/autojump.sh
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    # bash_completion installation installed with macports
    if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
        source /opt/local/etc/profile.d/bash_completion.sh
    fi

    #for git
    if [ -f /opt/local/share/git-core/contrib/completion/git-completion.bash ]; then
        source /opt/local/share/git-core/contrib/completion/git-completion.bash
    fi

    # Setting PATH for Python 2.7 installed from python.org
    PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
fi


## Other 
if [ $(uname -s) = "Linux" ]; then

    # autojump for bash (ubuntu package)
    if [ -f /usr/share/autojump/autojump.bash ]; then
        . /usr/share/autojump/autojump.bash
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    ## On Arch Linux it is installed under /usr/etc/
    if [ -f /usr/etc/profile.d/autojump.bash ]; then
        . /usr/etc/profile.d/autojump.bash
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    #if reboot required tell me (Ubuntu)
    if [ -f /var/run/reboot-required ]; then
        echo 'Reboot required'
    fi 
fi

## Add home bin to the PATH
if [ -d ~/bin ]; then
  export PATH=$PATH:$HOME"/bin"
fi

## Computer specific additional profile options
if [ -f ~/.bash_profile2 ]; then
    source ~/.bash_profile2
fi

## Functions
if [ -f ~/.bash/funcs ]; then
    source ~/.bash/funcs
fi

## Aliases
if [ -f ~/.bash/aliases ]; then
    source ~/.bash/aliases
fi

## addtional program settings
if [ -f ~/programs/.bashrc ]; then
    source ~/programs/.bashrc 
fi

export PATH
