#PS1='\u@\h:\W \$ '
PS1='\[\033[1m\]\u@\h \[\033[0;31m\]\W \$ \[\033[00m\]'

# make bash history unlimited
export HISTFILESIZE=
export HISTSIZE=

# set editor as vim
export EDITOR="vim"
export PAGER="less"

#vi-compatiple command line
#set -o vi

# Language preferences
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

if [ -e "$HOME"/local ]; then
    export LD_LIBRARY_PATH="$HOME"/local/lib:"$HOME"/local/lib64:"$LD_LIBRARY_PATH"
fi

export CLICOLOR=1
## White background
#export LSCOLORS=ExFxCxDxBxegedabagacad
## Dark background
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

## Mac OS X dependent settings
if [ $(uname -s) = "Darwin" ]; then

    # QT bin on osx
    #PATH=$PATH:$HOME"/QtSDK/Desktop/Qt/474/gcc/bin"

    # Java home
    export JAVA_HOME=$(/usr/libexec/java_home)

    # autojump for bash installed with macports
    if [ -f /usr/local/etc/profile.d/autojump.sh ]; then
	source /usr/local/etc/profile.d/autojump.sh
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    # bash_completion installation installed with macports
    if [ -f /usr/local/etc/bash_completion ]; then
	source /usr/local/etc/bash_completion
    fi

fi


## Other 
if [ $(uname -s) = "Linux" ]; then

    # autojump for bash (ubuntu package)
    if [ -f /usr/share/autojump/autojump.bash ]; then
        . /usr/share/autojump/autojump.bash
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    ## On Arch Linux it is installed under /usr/etc/
    if [ -f /usr/etc/profile.d/autojump.bash ]; then
        . /usr/etc/profile.d/autojump.bash
        export AUTOJUMP_IGNORE_CASE=1
        export AUTOJUMP_KEEP_SYMLINKS=1
    fi

    #if reboot required tell me (Ubuntu)
    if [ -f /var/run/reboot-required ]; then
        echo 'Reboot required'
    fi 
fi

## Add home bin to the PATH
if [ -d ~/local/bin ]; then
  export PATH=$PATH:$HOME"/bin"
fi

if [ -d ~/.bash/profile.d ]; then
    for f in ~/.bash/profile.d/*; do
        source $f
    done
fi

## Computer specific additional profile options
if [ -f ~/.bash_profile2 ]; then
    source ~/.bash_profile2
fi

## addtional program settings
if [ -f ~/programs/.bashrc ]; then
    source ~/programs/.bashrc 
fi

export PATH
